spring:
  application:
    name: opsWar

  datasource:
    url: jdbc:h2:mem:resource-db
    driver-class-name: org.h2.Driver
    username: root
    password: ""

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  h2:
    console:
      enabled: true
      path: /h2-console

appinmemory:
  users:
    - username: user
      password: user
      role: user
    - username: admin
      password: admin
      role: admin

logging:
  file:
    name: logs/resource-app.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: INFO

server:
  port: 8084
